[package]
name = "rrgeo-warp"
version = "0.1.0"
authors = ["Grant Miner <ggcode1@users.noreply.github.com>"]
edition = "2018"

[dependencies]
lazy_static = "^1.4"
reverse_geocoder = { path = "../reverse-geocoder" }
serde = "^1.0"
serde_derive = "^1.0"
time = "^0.2.16"
tokio = { version = "1.0.1", features = ["full"] }
warp = "^0.3.1"

[dev-dependencies]
bytes = "^1.0.1"

[[bin]]
name = "rrgeo-warp"
path = "src/warp.rs"
